const VACANCIES_FETCH_REQUESTED = 'VACANCIES_FETCH_REQUESTED';
const VACANCIES_FETCH_SUCCEEDED = 'VACANCIES_FETCH_SUCCEEDED';
const VACANCIES_FETCH_FAILED = 'VACANCIES_FETCH_FAILED';

export {
  VACANCIES_FETCH_REQUESTED,
  VACANCIES_FETCH_SUCCEEDED,
  VACANCIES_FETCH_FAILED
}